# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='wishful_module_simple.proto.messages_pb2',
  serialized_pb=_b('\n\x0emessages.proto\x12(wishful_module_simple.proto.messages_pb2\"\xd8\x01\n\nStatistics\x12\x10\n\x08\x64\x61tetime\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x11\n\tinterface\x18\x04 \x02(\t\x12\x11\n\ttx_frames\x18\x05 \x02(\r\x12\x11\n\trx_frames\x18\x06 \x02(\r\x12\x13\n\x0b\x64rop_frames\x18\x07 \x02(\r\x12\x10\n\x08tx_bytes\x18\x08 \x02(\r\x12\x10\n\x08rx_bytes\x18\t \x02(\r\x12\x12\n\ndrop_bytes\x18\n \x02(\r\x12\x16\n\x0e\x61vg_throughput\x18\x0b \x02(\x02\"K\n\x07\x43hannel\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0e\n\x06number\x18\x02 \x02(\r\x12\n\n\x02\x66l\x18\x04 \x02(\x02\x12\n\n\x02\x66\x63\x18\x05 \x02(\x02\x12\n\n\x02\x66h\x18\x06 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STATISTICS = _descriptor.Descriptor(
  name='Statistics',
  full_name='wishful_module_simple.proto.messages_pb2.Statistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='wishful_module_simple.proto.messages_pb2.Statistics.datetime', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='wishful_module_simple.proto.messages_pb2.Statistics.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='wishful_module_simple.proto.messages_pb2.Statistics.name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interface', full_name='wishful_module_simple.proto.messages_pb2.Statistics.interface', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_frames', full_name='wishful_module_simple.proto.messages_pb2.Statistics.tx_frames', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_frames', full_name='wishful_module_simple.proto.messages_pb2.Statistics.rx_frames', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drop_frames', full_name='wishful_module_simple.proto.messages_pb2.Statistics.drop_frames', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tx_bytes', full_name='wishful_module_simple.proto.messages_pb2.Statistics.tx_bytes', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rx_bytes', full_name='wishful_module_simple.proto.messages_pb2.Statistics.rx_bytes', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drop_bytes', full_name='wishful_module_simple.proto.messages_pb2.Statistics.drop_bytes', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_throughput', full_name='wishful_module_simple.proto.messages_pb2.Statistics.avg_throughput', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=277,
)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='wishful_module_simple.proto.messages_pb2.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='wishful_module_simple.proto.messages_pb2.Channel.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='wishful_module_simple.proto.messages_pb2.Channel.number', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fl', full_name='wishful_module_simple.proto.messages_pb2.Channel.fl', index=2,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fc', full_name='wishful_module_simple.proto.messages_pb2.Channel.fc', index=3,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fh', full_name='wishful_module_simple.proto.messages_pb2.Channel.fh', index=4,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=354,
)

DESCRIPTOR.message_types_by_name['Statistics'] = _STATISTICS
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL

Statistics = _reflection.GeneratedProtocolMessageType('Statistics', (_message.Message,), dict(
  DESCRIPTOR = _STATISTICS,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:wishful_module_simple.proto.messages_pb2.Statistics)
  ))
_sym_db.RegisterMessage(Statistics)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), dict(
  DESCRIPTOR = _CHANNEL,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:wishful_module_simple.proto.messages_pb2.Channel)
  ))
_sym_db.RegisterMessage(Channel)


# @@protoc_insertion_point(module_scope)
